package: d2u_courses
version: '3.4.1'
author: Tobias Krais

page:
    title: 'translate:d2u_courses'
    perm: 'd2u_courses[]'
    icon: rex-icon fa-leanpub
    subpages:
        course: { title: 'translate:d2u_courses_courses', icon: rex-icon fa-leanpub }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category, perm: 'd2u_courses[categories]' }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'd2u_courses[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'd2u_courses[settings]' }
        help: { title: 'translate:package_hhelp', icon: rex-icon rex-icon-help, itemClass: pull-right }

requires:
    redaxo: '>=5.10.0'
    packages:
        d2u_helper: '>=1.8.5'
        phpmailer: '>=2.12.0'
        sprog: '>=1.0.0'
        url: '>=2.1'
        yrewrite: '>=2.0.1'
    php: '>=7.4'

conflicts:
    packages:
        multinewsletter: '<3.2.1'

default_config:
    allow_company: 'true'
    forward_single_course: 'active'

installer_ignore:
    - .github