package: d2u_courses
version: '3.0.2'
author: Tobias Krais

page:
    title: 'translate:d2u_courses'
    perm: d2u_courses[]
    icon: rex-icon fa-leanpub
    subpages:
        course: { title: 'translate:d2u_courses_courses', icon: rex-icon fa-leanpub }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category, perm: d2u_courses[categories] }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_courses[settings] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_courses[settings] }

requires:
    packages:
        d2u_helper: '>=1.4.6'
        sprog: '>=1.0.0'
        url: '>=1.0.1'
        yrewrite: '>=2.0.1'